on: push
name: Run Stale Bot on Issue Comments
jobs:
  build:
    name: workflow name
    runs-on: ubuntu-latest
    steps:
      - name: npm install
        run: npm ci
      - name: local action name
        uses: mgwalker/_stale-test@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
